version: '3.7'

services:

  httpnotice:
    image: http-notice-live:latest
    build:
      context: .
      args:
        NG_BUILD_OPTS: build:live
    container_name: httpd-notice-live
    ports:
    - "5082:80"
